### ISSUE TITLE
document using + sign

### ISSUE THREAD

**Issue by btopro** [keithamus/jwerty#69]
is it possible to use + as the trigger key or not because it's a special glue character for jwerty commands?

Trying to do something like this `ctrl+shift++`

**Comment by keithamus** [comment]
You can use the literal word `plus`, as in: `ctrl+shift+plus` - but there is specific code to make `ctrl+shift++` work also, so both forms should work.

**Comment by btopro** [comment]
cool. Might want to add that to the readme / docs though as it's not mentioned anywhere I can find http://keithamus.github.io/jwerty/

**Comment by keithamus** [comment]
Great idea! How would you like to send a PR to correct the docs?

**Comment by btopro** [comment]
PR open
